import type { Metadata } from 'next';
import { JetBrains_Mono, Manrope } from 'next/font/google';

import './globals.css';

const ManropeSans = Manrope({
	variable: '--font-manrope-sans',
	subsets: ['latin'],
});
const JetBrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mone',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${ManropeSans.variable} ${JetBrainsMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
