import type { Metadata } from 'next';
import { JetBrains_Mono, Manrope } from 'next/font/google';

import './globals.css';

const ManropeSans = Manrope({
	variable: '--font-manrope-sans',
	subsets: ['latin'],
});
const JetBrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mone',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Nivox Lab',
	description:
		'Generated by create next applibrary of ready-made ui blocks to speed up development',
	icons: {
		icon: '/favicon/favicon.svg',
		shortcut: '/favicon/favicon.svg',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${ManropeSans.variable} ${JetBrainsMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
