import type { Metadata } from 'next';
import { JetBrains_Mono, Manrope, Roboto_Condensed } from 'next/font/google';

import AnimatedLayout from './(public)/AnimatedLayout';

import './globals.css';

const ManropeSans = Manrope({
	variable: '--font-manrope-sans',
	subsets: ['latin'],
});
const JetBrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mone',
	subsets: ['latin'],
});
const RobotoCondensed = Roboto_Condensed({
	variable: '--font-roboto-cond',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Nivox UI',
	description:
		'Generated by create next applibrary of ready-made ui blocks to speed up development',
	icons: {
		icon: '/favicon/favicon.svg',
		shortcut: '/favicon/favicon.svg',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${ManropeSans.variable} ${JetBrainsMono.variable} ${RobotoCondensed.variable} antialiased`}
			>
				<AnimatedLayout>{children}</AnimatedLayout>
			</body>
		</html>
	);
}
